#!/usr/bin/env bash
# Generated by Trisixt. Run with GCP_PROJECT_ID [NEW_CREDENTIAL_FILE].
set -euo pipefail
umask 077
command -v gcloud >/dev/null || { echo 'Install the Google Cloud CLI first.' >&2; exit 1; }
PROJECT_ID="${1:?Usage: bash trisixt_android_gcloud_setup.sh GCP_PROJECT_ID [NEW_CREDENTIAL_FILE]}"
[[ "$PROJECT_ID" =~ ^[a-z][a-z0-9-]{4,28}[a-z0-9]$ ]] || { echo 'Invalid Google Cloud project ID.' >&2; exit 1; }
PUSH_ENDPOINT=@@ENDPOINT@@
PUSH_AUDIENCE=@@AUDIENCE@@
CONFIGURED_ACCOUNT=@@ACCOUNT@@
INSTANCE_ID=@@INSTANCE@@
SA_EMAIL="${CONFIGURED_ACCOUNT:-trisixt-play-api@${PROJECT_ID}.iam.gserviceaccount.com}"
SA_ACCOUNT="${SA_EMAIL%%@*}"
SA_PROJECT="${SA_EMAIL#*@}"
SA_PROJECT="${SA_PROJECT%.iam.gserviceaccount.com}"
TOPIC_NAME="trisixt-play-${INSTANCE_ID}"
SUBSCRIPTION_NAME="${TOPIC_NAME}-push"
[[ -n "$(gcloud auth list --filter=status:ACTIVE --format='value(account)')" ]] || gcloud auth login
# All commands select their project explicitly and preserve the caller's gcloud configuration.
gcloud services enable iam.googleapis.com pubsub.googleapis.com androidpublisher.googleapis.com --project="$PROJECT_ID"
if ! gcloud iam service-accounts describe "$SA_EMAIL" --project="$SA_PROJECT" >/dev/null 2>&1; then
  gcloud iam service-accounts create "$SA_ACCOUNT" --display-name='Trisixt Google Play' --project="$SA_PROJECT"
fi
PROJECT_NUMBER="$(gcloud projects describe "$PROJECT_ID" --format='value(projectNumber)')"
gcloud beta services identity create --service=pubsub.googleapis.com --project="$PROJECT_ID" >/dev/null
gcloud iam service-accounts add-iam-policy-binding "$SA_EMAIL" --project="$SA_PROJECT" \
  --member="serviceAccount:service-${PROJECT_NUMBER}@gcp-sa-pubsub.iam.gserviceaccount.com" \
  --role=roles/iam.serviceAccountTokenCreator --condition=None >/dev/null
if ! gcloud pubsub topics describe "$TOPIC_NAME" --project="$PROJECT_ID" >/dev/null 2>&1; then
  gcloud pubsub topics create "$TOPIC_NAME" --project="$PROJECT_ID"
fi
gcloud pubsub topics add-iam-policy-binding "$TOPIC_NAME" --project="$PROJECT_ID" \
  --member='serviceAccount:google-play-developer-notifications@system.gserviceaccount.com' \
  --role=roles/pubsub.publisher --condition=None >/dev/null
if gcloud pubsub subscriptions describe "$SUBSCRIPTION_NAME" --project="$PROJECT_ID" >/dev/null 2>&1; then
  gcloud pubsub subscriptions modify-push-config "$SUBSCRIPTION_NAME" --project="$PROJECT_ID" \
    --push-endpoint="$PUSH_ENDPOINT" --push-auth-service-account="$SA_EMAIL" --push-auth-token-audience="$PUSH_AUDIENCE"
else
  gcloud pubsub subscriptions create "$SUBSCRIPTION_NAME" --project="$PROJECT_ID" --topic="$TOPIC_NAME" \
    --message-retention-duration=7d --push-endpoint="$PUSH_ENDPOINT" \
    --push-auth-service-account="$SA_EMAIL" --push-auth-token-audience="$PUSH_AUDIENCE"
fi
# A credential file is optional when the server uses Application Default Credentials.
if [[ -n "${2:-}" ]]; then
  [[ ! -e "$2" ]] || { echo 'Credential destination already exists; refusing to replace it.' >&2; exit 1; }
  gcloud iam service-accounts keys create "$2" --iam-account="$SA_EMAIL" --project="$SA_PROJECT"
  chmod 600 "$2"
  printf 'Mount the credential file read-only and reference its path in TRISIXT_IAP_PROFILES.\n'
fi
printf '\nSet these server environment variables (then restart the service):\n'
printf 'GOOGLE_PUBSUB_AUDIENCE=%q\nGOOGLE_PUBSUB_SERVICE_ACCOUNT_EMAIL=%q\n' "$PUSH_AUDIENCE" "$SA_EMAIL"
printf '\nGoogle Play Console RTDN topic: projects/%s/topics/%s\n' "$PROJECT_ID" "$TOPIC_NAME"
printf 'Invite %s in Play Console; grant app read, financial/order read, and manage orders/subscriptions permissions.\n' "$SA_EMAIL"
printf 'Enable subscription, voided purchase and one-time product notifications; send a test notification.\n'
printf 'Configure the package name and credentials in TRISIXT_IAP_PROFILES and enable instance revenue collection.\n'
